[project]
name = "pokemon-typing-nash"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nashpy>=0.0.41",
    "numpy>=2.2.5",
]
